// Generated by CoffeeScript 1.6.3
(function() {
  var CONFIG_DIR, argv, configFile, optimist, path, service;

  path = require('path');

  service = require('./service');

  configFile = require('./config_file');

  CONFIG_DIR = path.join(process.env.HOME, '.dnster');

  argv = (optimist = require('optimist').usage('Manage .dev DNS forwarding.\nUsage: $0 run').options('c', {
    string: true,
    alias: 'config',
    "default": path.join(process.env.HOME, '.dnster'),
    describe: 'config directory'
  }).options('w', {
    boolean: true,
    alias: 'watch',
    "default": true,
    describe: 'watch config for changes'
  })).argv;

  switch (argv._[0]) {
    case 'run':
      configFile.read(argv.config, function(err, config) {
        if (err != null) {
          console.error(err);
          return process.exit(1);
        } else {
          return service.run(config, argv.watch);
        }
      });
      break;
    default:
      optimist.showHelp();
      process.exit(1);
  }

}).call(this);
