// Generated by CoffeeScript 1.6.3
(function() {
  var CONFIG_DIR, CONFIG_FILE, argv, optimist, path, service;

  path = require('path');

  service = require('./service');

  CONFIG_DIR = path.join(process.env.HOME, '.dnster');

  CONFIG_FILE = path.join(CONFIG_DIR, 'config.json');

  argv = (optimist = require('optimist').usage('Manage .dev DNS forwarding.\nUsage: $0 run').options('c', {
    string: true,
    alias: 'config',
    "default": CONFIG_FILE
  }).options('w', {
    boolean: true,
    alias: 'watch',
    "default": true
  })).argv;

  switch (argv._[0]) {
    case 'run':
      service.run(argv.config, argv.watch);
      break;
    default:
      optimist.showHelp();
      process.exit(1);
  }

}).call(this);
