// Generated by CoffeeScript 1.6.3
(function() {
  var errorPage, fs, http, httpProxy, path, proxy, server, _ref;

  http = require('http');

  httpProxy = require('http-proxy');

  fs = require('fs');

  path = require('path');

  _ref = {}, proxy = _ref.proxy, server = _ref.server, errorPage = _ref.errorPage;

  module.exports = {
    reload: function(routes) {
      this.stop();
      errorPage = fs.readFileSync(path.join(__dirname, '..', 'error.html'), 'utf8');
      proxy = httpProxy.createProxyServer();
      server = http.createServer(function(req, res) {
        var target;
        target = routes[req.headers.host];
        return proxy.web(req, res, {
          target: "http://" + target
        }, function(err) {
          var content;
          content = errorPage.replace('{{host}}', req.headers.host).replace('{{target}}', target || '~~ not configured ~~');
          res.setHeader('Content-Length', content.length);
          res.setHeader('Content-Type', 'text/html');
          return res.end(content, 5000);
        });
      });
      return server.listen(80);
    },
    stop: function() {
      if (server == null) {
        return;
      }
      server.close();
      server = null;
      return proxy = null;
    }
  };

}).call(this);
