// Generated by CoffeeScript 1.6.3
(function() {
  var fs, httpProxy, https, path, proxy, server, sslCertBuilder, _ref;

  https = require('https');

  fs = require('fs');

  httpProxy = require('http-proxy');

  sslCertBuilder = require('./ssl_cert_builder');

  path = require('path');

  _ref = {}, proxy = _ref.proxy, server = _ref.server;

  module.exports = {
    reload: function(files, routes) {
      var errorPage;
      this.stop();
      errorPage = fs.readFileSync(path.join(__dirname, '..', 'error.html'), 'utf8');
      return sslCertBuilder.rebuild(files, routes, function(err) {
        var options;
        if (err != null) {
          throw err;
        }
        proxy = httpProxy.createProxyServer({
          xfwd: true
        });
        options = {
          key: fs.readFileSync(files.site.key),
          cert: fs.readFileSync(files.site.pem),
          ca: [fs.readFileSync(files.ca.pem)]
        };
        server = https.createServer(options, function(req, res) {
          var target;
          target = routes[req.headers.host];
          return proxy.web(req, res, {
            target: "http://" + target
          }, function(err) {
            var content;
            content = errorPage.replace('{{host}}', req.headers.host).replace('{{target}}', target || '~~ not configured ~~');
            res.setHeader('Content-Length', content.length);
            res.setHeader('Content-Type', 'text/html');
            return res.end(content, 5000);
          });
        });
        return server.listen(443);
      });
    },
    stop: function() {
      if (server == null) {
        return;
      }
      server.close();
      server = null;
      return proxy = null;
    }
  };

}).call(this);
