// Generated by CoffeeScript 1.6.3
(function() {
  var fs, httpProxy, https, proxy, server, sslCertBuilder, _ref;

  https = require('https');

  fs = require('fs');

  httpProxy = require('http-proxy');

  sslCertBuilder = require('./ssl_cert_builder');

  _ref = {}, proxy = _ref.proxy, server = _ref.server;

  module.exports = {
    reload: function(files, routes) {
      this.stop();
      return sslCertBuilder.rebuild(files, routes, function(err) {
        var options;
        if (err != null) {
          throw err;
        }
        proxy = httpProxy.createProxyServer({
          xfwd: true
        });
        options = {
          key: fs.readFileSync(files.site.key),
          cert: fs.readFileSync(files.site.pem),
          ca: [fs.readFileSync(files.ca.pem)]
        };
        server = https.createServer(options, function(req, res) {
          return proxy.web(req, res, {
            target: "http://" + routes[req.headers.host]
          }, function(err) {
            return res.end(err.stack || err, 500);
          });
        });
        return server.listen(443);
      });
    },
    stop: function() {
      if (server == null) {
        return;
      }
      server.close();
      server = null;
      return proxy = null;
    }
  };

}).call(this);
