// Generated by CoffeeScript 1.6.3
(function() {
  var http, httpProxy, proxy, server, _ref;

  http = require('http');

  httpProxy = require('http-proxy');

  _ref = {}, proxy = _ref.proxy, server = _ref.server;

  module.exports = {
    reload: function(routes) {
      this.stop();
      proxy = httpProxy.createProxyServer();
      server = http.createServer(function(req, res) {
        return proxy.web(req, res, {
          target: "http://" + routes[req.headers.host]
        });
      });
      return server.listen(80);
    },
    stop: function() {
      if (server == null) {
        return;
      }
      server.close();
      server = null;
      return proxy = null;
    }
  };

}).call(this);
